{% set name = "qtwebsockets" %}
{% set version = "6.7.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://download.qt.io/official_releases/qt/{{ version.rpartition('.')[0] }}/{{ version }}/submodules/{{ name }}-everywhere-src-{{ version }}.tar.xz
    sha256: 5bde4af6ec9ce8c8632b782ab77b82d910721be2c714e6d38902521bcd1d215f
    folder: {{ name }}

build:
  number: 0
  skip: True  # [ppc64le or s390x]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}
  ignore_run_exports:
    - qtshadertools

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libdrm-devel') }}               # [linux]
    - {{ cdt('libglvnd-glx') }}               # [linux and not x86_64]
    - {{ cdt('libglvnd-egl') }}               # [linux and not x86_64]
    - {{ cdt('libice-devel') }}               # [linux]
    - {{ cdt('libsm-devel') }}                # [linux]
    - {{ cdt('libx11-devel') }}               # [linux]
    - {{ cdt('libxau-devel') }}               # [linux]
    - {{ cdt('mesa-libgl-devel') }}           # [linux]
    - {{ cdt('mesa-libgbm') }}                # [linux]
    - {{ cdt('mesa-libegl-devel') }}          # [linux]
    - {{ cdt('mesa-dri-drivers') }}           # [linux]
    - {{ cdt('xcb-util-devel') }}             # [linux]
    - {{ cdt('xcb-util-image-devel') }}       # [linux]
    - {{ cdt('xcb-util-keysyms-devel') }}     # [linux]
    - {{ cdt('xcb-util-renderutil-devel') }}  # [linux]
    - {{ cdt('xcb-util-wm-devel') }}          # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}       # [linux]
    - {{ cdt('libselinux') }}                 # [linux]
    - {{ cdt('libxext') }}                    # [linux]
    - {{ cdt('libxdamage') }}                 # [linux]
    - {{ cdt('libxfixes') }}                  # [linux]
    - {{ cdt('libxxf86vm') }}                 # [linux]
    - pkg-config  # [unix]
    - bison       # [linux]
    - flex        # [linux]
    - gperf       # [linux]
    - jom         # [win]
    - m2-bison    # [win]
    - m2-flex     # [win]
    - m2-gperf    # [win]
    - cmake
    - ninja
    - perl

  host:
    - qtbase {{ version }}
    - qtdeclarative {{ version }}

  run_constrained:
    - qt-main >={{ version }},<7
    - qt >={{ version }},<7

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - {{ cdt('libdrm-devel') }}               # [linux]
    - {{ cdt('libglvnd-glx') }}               # [linux and not x86_64]
    - {{ cdt('libglvnd-egl') }}               # [linux and not x86_64]
    - {{ cdt('libice-devel') }}               # [linux]
    - {{ cdt('libsm-devel') }}                # [linux]
    - {{ cdt('libx11-devel') }}               # [linux]
    - {{ cdt('libxau-devel') }}               # [linux]
    - {{ cdt('mesa-libgl-devel') }}           # [linux]
    - {{ cdt('mesa-libgbm') }}                # [linux]
    - {{ cdt('mesa-libegl-devel') }}          # [linux]
    - {{ cdt('mesa-dri-drivers') }}           # [linux]
    - {{ cdt('xcb-util-devel') }}             # [linux]
    - {{ cdt('xcb-util-image-devel') }}       # [linux]
    - {{ cdt('xcb-util-keysyms-devel') }}     # [linux]
    - {{ cdt('xcb-util-renderutil-devel') }}  # [linux]
    - {{ cdt('xcb-util-wm-devel') }}          # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}       # [linux]
    - {{ cdt('libselinux') }}                 # [linux]
    - {{ cdt('libxext') }}                    # [linux]
    - {{ cdt('libxdamage') }}                 # [linux]
    - {{ cdt('libxfixes') }}                  # [linux]
    - {{ cdt('libxxf86vm') }}                 # [linux]
  files:
    - run_qt_test.sh    # [unix]
    - run_qt_test.bat   # [win]
    - test/test_qtwebsockets.cpp
    - test/CMakeLists.txt
  commands:
    - ./run_qt_test.sh  # [unix]
    - run_qt_test.bat   # [win]
    {% for each_qt_lib in ["WebSockets"] %}
    - test -d $PREFIX/include/qt6/Qt{{ each_qt_lib }}                           # [unix]
    - test -f $PREFIX/lib/libQt6{{ each_qt_lib }}${SHLIB_EXT}                   # [unix]
    - if not exist %PREFIX%\\Library\\include\\qt6\\Qt{{ each_qt_lib }} exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\Qt6{{ each_qt_lib }}.lib exit 1      # [win]
    - if not exist %PREFIX%\\Library\\bin\\Qt6{{ each_qt_lib }}.dll exit 1      # [win]
    {% endfor %}

about:
  home: https://www.qt.io/
  license: LGPL-3.0-only
  license_file: {{ name }}/LICENSES/LGPL-3.0-only.txt
  license_family: LGPL
  summary: Cross-platform application and UI framework ({{ name[2:] }} libraries).
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time ({{ name[2:] }} libraries).
  doc_url: https://doc.qt.io/
  dev_url: https://github.com/qt/{{ name }}
