{% set name = "qtwebsockets" %}
{% set version = "6.7.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://download.qt.io/official_releases/qt/{{ version.rpartition('.')[0] }}/{{ version }}/submodules/{{ name }}-everywhere-src-{{ version }}.tar.xz
    sha256: ba03007db7ee68a5bc3e3bd1d71e11f3e1f84e470bcb8c54cd7c01bbe1c5990e
    folder: {{ name }}

build:
  number: 0
  skip: True  # [ppc64le or s390x or (osx and x86_64)]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}
  ignore_run_exports:
    - qtshadertools

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # TODO: map CDT libdrm-devel to new X11 package
    # - { cdt('libdrm-devel') }
    # TODO: map CDT mesa-libgbm to new X11 package
    # - { cdt('mesa-libgbm') }
    # TODO: map CDT mesa-libegl-devel to new X11 package
    # - { cdt('mesa-libegl-devel') }
    # TODO: map CDT libselinux to new X11 package
    # - { cdt('libselinux') }
    - pkg-config  # [unix]
    - bison       # [linux]
    - flex        # [linux]
    - gperf       # [linux]
    - jom         # [win]
    - m2-bison    # [win]
    - m2-flex     # [win]
    - m2-gperf    # [win]
    - cmake
    - ninja
    - perl

  host:
    - qtbase {{ version }}
    - qtdeclarative {{ version }}

    - libglx
    - libegl
    - xorg-libice
    - xorg-libsm
    - xorg-libx11
    - xorg-libxau
    - libgl-devel
    - mesa-dri-drivers
    - xcb-util
    - xcb-util-image
    - xcb-util-keysyms
    - xcb-util-renderutil
    - xcb-util-wm
    - xorg-xproto
    - xorg-libxext
    - xorg-libxdamage
    - xorg-libxfixes
    - xorg-libxxf86vm
    - libglx
    - libegl
    - xorg-libice
    - xorg-libsm
    - xorg-libx11
    - xorg-libxau
    - libgl-devel
    - mesa-dri-drivers
    - xcb-util
    - xcb-util-image
    - xcb-util-keysyms
    - xcb-util-renderutil
    - xcb-util-wm
    - xorg-xproto
    - xorg-libxext
    - xorg-libxdamage
    - xorg-libxfixes
    - xorg-libxxf86vm
  run_constrained:
    - qt-main >={{ version }},<7
    - qt >={{ version }},<7

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    # TODO: map CDT libdrm-devel to new X11 package
    # - { cdt('libdrm-devel') }
    # TODO: map CDT mesa-libgbm to new X11 package
    # - { cdt('mesa-libgbm') }
    # TODO: map CDT mesa-libegl-devel to new X11 package
    # - { cdt('mesa-libegl-devel') }
    # TODO: map CDT libselinux to new X11 package
    # - { cdt('libselinux') }
  files:
    - run_qt_test.sh    # [unix]
    - run_qt_test.bat   # [win]
    - test/test_qtwebsockets.cpp
    - test/CMakeLists.txt
  commands:
    - ./run_qt_test.sh  # [unix]
    - run_qt_test.bat   # [win]
    {% for each_qt_lib in ["WebSockets"] %}
    - test -d $PREFIX/include/qt6/Qt{{ each_qt_lib }}                           # [unix]
    - test -f $PREFIX/lib/libQt6{{ each_qt_lib }}${SHLIB_EXT}                   # [unix]
    - if not exist %PREFIX%\\Library\\include\\qt6\\Qt{{ each_qt_lib }} exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\Qt6{{ each_qt_lib }}.lib exit 1      # [win]
    - if not exist %PREFIX%\\Library\\bin\\Qt6{{ each_qt_lib }}.dll exit 1      # [win]
    {% endfor %}

about:
  home: https://www.qt.io/
  license: LGPL-3.0-only
  license_file: {{ name }}/LICENSES/LGPL-3.0-only.txt
  license_family: LGPL
  summary: Cross-platform application and UI framework ({{ name[2:] }} libraries).
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time ({{ name[2:] }} libraries).
  doc_url: https://doc.qt.io/
  dev_url: https://github.com/qt/{{ name }}
